# Generated by Django 5.0.6 on 2024-07-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking_booked_on_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dep_name',
        ),
    ]
